# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: bundler # See documentation for possible values
    open-pull-requests-limit: 50
    directory: "/" # Location of package manifests
    versioning-strategy: increase
    schedule:
      interval: "daily"
      timezone: "America/Vancouver"
      time: "08:00"
    groups:
      rails:
        update-types:
        - "major"
        - "minor"
        - "patch"
        patterns:
        - "rails"
        - "action*"
        - "active*"
      patches:
        patterns:
        - "*"
        update-types:
        - "patch"
      minor:
        patterns:
        - "*"
        update-types:
        - "minor"
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 1