name: Minitest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.4', 'head']
        rails-version: ['8.0', '8.1', 'main']
    
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - name: Run Minitest
      continue-on-error: ${{ matrix.rails-version == 'main' }}
      run: |
        bundle exec ruby test/expect_query_test.rb
        bundle exec ruby test/multi_store_test.rb
